export const AUTH_LOADING_SET_VERIFYING = 'AUTH_LOADING_SET_VERIFYING';
export const AUTH_LOADING_SET_LOGGINGIN = 'AUTH_LOADING_SET_LOGGINGIN';
export const AUTH_CLEAR = 'AUTH_CLEAR';

export const AUTH_VERIFIED = 'AUTH_VERIFIED';
export const AUTH_VERIFIED_FAILED = 'AUTH_VERIFIED_FAILED';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
